pizzeria/pizzas/urls.py
"""定义pizzas的URL模式"""

from django.conf.urls import url
from . import views

urlpatterns = [
	#主页
	url(r'^$',views.index,name='index'),
	
	#显示披萨种类页面
	url(r'^pizzas/$',views.pizzas,name='pizzas'),
	
	#披萨介绍页面
	url(r'^pizzas/(?P<pizza_id>\d+)/$',views.pizza,name='pizza'),
	
	#添加新的披萨的页面
	url(r'^new_pizza/$',views.new_pizza,name='new_pizza'),
	
	#添加新的介绍的页面
	url(r'^new_topping/(?P<pizza_id>\d+)/$',views.new_topping,
											name='new_topping'),
											
	#添加编辑条目的页面
	url(r'^edit_topping/(?P<topping_id>\d+)/$',views.edit_topping,
											name='edit_topping'),
	]

pizzeria/pizzeria/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('pizzas.urls',namespace='pizzas')),
    url(r'^users/',include('users.urls',namespace='users')),
]

pizzeria/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
	name = models.CharField(max_length=100)
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name
		
		
class Topping(models.Model):
	pizza = models.ForeignKey(Pizza)
	name = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Pizza,Topping
from .forms import PizzaForm,ToppingForm
# Create your views here.
def index(request):
	"""披萨店主页"""
	return render(request,'pizzas/index.html')
	
def pizzas(request):
	"""显示披萨种类"""
	pizzas = Pizza.objects.order_by('date_added')
	context = {'pizzas':pizzas}
	return render(request,'pizzas/pizzas.html',context)
	
	
def pizza(request,pizza_id):
	"""显示每个披萨和对应介绍"""
	pizza = Pizza.objects.get(id = pizza_id)
	toppings = pizza.topping_set.order_by('-date_added')
	context = {'pizza':pizza,'toppings':toppings}
	return render(request,'pizzas/pizza.html',context)


def new_pizza(request):
	"""添加新的披萨种类"""
	if request.method != 'POST':
		#未提交数据：创建一个新表单
		form = PizzaForm()
	else:
		#post提交的数据，对数据进行处理
		form = PizzaForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('pizzas:pizzas'))
			
	context = {'form':form}
	return render(request,'pizzas/new_pizza.html',context)
	
	
def new_topping(request,pizza_id):
	"""在披萨中添加介绍"""
	pizza = Pizza.objects.get(id=pizza_id)
	
	if request.method != 'POST':
		form = ToppingForm()
	else:
		form = ToppingForm(data=request.POST)
		if form.is_valid():
			new_topping = form.save(commit=False)
			new_topping.pizza = pizza
			new_topping.save()
			return HttpResponseRedirect(reverse('pizzas:pizza',
											args=[pizza_id]))
											
	context = {'pizza':pizza,'form':form}
	return render(request,'pizzas/new_topping.html',context)
	

def edit_topping(request,topping_id):
	"""编辑介绍"""
	topping = Topping.objects.get(id = topping_id)
	pizza = topping.pizza
	
	if request.method != 'POST':
		form = ToppingForm(instance=topping)
	else:
		form = ToppingForm(instance=topping,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('pizzas:pizza',
												args=[pizza.id]))
	
	context = {'topping':topping,'pizza':pizza,'form':form}
	return render(request,'pizzas/edit_topping.html',context)
	
	
	
	
	

pizzeria/pizzas/templates/pizzas/base.html
<p>
	<a href="{% url 'pizzas:index' %}">披萨店</a> -
	<a href="{% url 'pizzas:pizzas' %}">披萨种类</a> -
	  {% if user.is_authenticated %}
	    你好，{{ user.username }}.
	    <a href="{% url 'users:logout' %}">注销</a>
	  {% else %}
	    <a href="{% url 'users:login' %}">登陆</a>
	  {% endif %}
</p>

{% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>这是一个关于披萨的主页披萨</p>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>披萨:{{ pizza }}</p>
  <p>介绍:</p>
    
  <ul>
    {% for topping in toppings %}
      <li>
	    <p>{{ topping.date_added|date:'M d,Y H:i' }}</p>
	    <p>{{ topping.name|linebreaks }}</p>
	    <p>
			<a href="{% url 'pizzas:edit_topping' topping.id %}">编辑介绍</a>
		</p>
	  </li>
	{% empty %}
      <li>暂无介绍</li>
    {% endfor %}
  </ul>
  <p>
	  <a href="{% url 'pizzas:new_topping' pizza.id %}">新增介绍</a>
  </p>
  
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>披萨</p>
    
  <ul>
    {% for pizza in pizzas %}
      <li>
	    <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
	  </li>
	{% empty %}
      <li>暂无披萨提供</li>
    {% endfor %}
  </ul>
  
  <a href="{% url 'pizzas:new_pizza' %}">增加一个披萨种类:</a>
  
{% endblock content %}